# Generated by Django 4.0.2 on 2022-02-21 11:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lock_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_by', models.CharField(max_length=30)),
                ('record_id', models.CharField(max_length=10)),
                ('lock_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.CharField(max_length=5)),
                ('ip_addresses', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_app_name', models.CharField(max_length=255)),
                ('app_id', models.CharField(max_length=10)),
                ('sub_app_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='users_activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_password_date', models.DateTimeField(null=True)),
                ('update_password_date', models.DateTimeField(null=True)),
                ('update_password_status', models.CharField(max_length=1)),
                ('login_status', models.CharField(max_length=1, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_level', models.CharField(max_length=1)),
                ('sub_app_id', models.CharField(max_length=2)),
                ('ruid_rights', models.CharField(max_length=4)),
                ('added_by', models.CharField(max_length=5, null=True)),
                ('added_date', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
