# Generated by Django 4.0.2 on 2022-02-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_systemusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemusers',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='systemusers',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
