# Generated by Django 4.0.2 on 2022-02-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_systemusers_email_alter_systemusers_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemusers',
            name='added_by',
            field=models.CharField(max_length=3),
        ),
    ]
