# Generated by Django 4.0.2 on 2022-02-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_transactions',
            name='payment_method',
            field=models.CharField(max_length=25),
        ),
    ]
